name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - master

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    name: Deploy Frontend
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          API_ENDPOINT: ${{ vars.API_ENDPOINT }}

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

  deploy-backend:
    runs-on: ubuntu-latest
    name: Deploy Backend API Worker
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: worker/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: worker

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: worker
          secrets: |
            SKYWAY_APP_ID
            SKYWAY_SECRET_KEY
        env:
          SKYWAY_APP_ID: ${{ secrets.SKYWAY_APP_ID }}
          SKYWAY_SECRET_KEY: ${{ secrets.SKYWAY_SECRET_KEY }}
